### ISSUE TITLE
npm fails to install

### ISSUE THREAD

**Issue by juanramb** [ditesh/node-unixlib#1]
It tries to do things in "/home/ditesh" 

Waf: Entering directory `/home/ditesh/code/node-unixlib/build'
Waf: Leaving directory`/home/ditesh/code/node-unixlib/build'
Traceback (most recent call last):
  File "/usr/bin/node-waf", line 18, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/share/nodejs/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/share/nodejs/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/share/nodejs/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/share/nodejs/wafadmin/Scripting.py", line 386, in build
    return build_impl(bld)
  File "/usr/share/nodejs/wafadmin/Scripting.py", line 405, in build_impl
    bld.compile()
  File "/usr/share/nodejs/wafadmin/Build.py", line 268, in compile
    os.chdir(self.bldnode.abspath())
OSError: [Errno 2] No such file or directory: '/home/ditesh/code/node-unixlib/build'
npm ERR! install failed Error: unixlib@0.1.0 preinstall: `node-waf configure && node-waf build`
npm ERR! install failed `sh` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/exec.js:25:18)
npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! Error: unixlib@0.1.0 preinstall: `node-waf configure && node-waf build`
npm ERR! `sh` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/exec.js:25:18)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! 
npm ERR! Failed at the unixlib@0.1.0 preinstall script.
npm ERR! This is most likely a problem with the unixlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure && node-waf build
npm ERR! You can get their info via:
npm ERR!     npm owner ls unixlib
npm ERR! There may be additional logging output above.
npm not ok

**Comment by ditesh** [comment]
Strange. Let me have a look and revert.

**Comment by ditesh** [comment]
I can't replicate it. In any case, I pushed some unpublished code and published 0.1.1.

Cheers.
