### ISSUE TITLE
Fails to build.

### ISSUE THREAD

**Issue by sebastient** [ditesh/node-unixlib#2]
Node v0.4.12
NPM 1.0.103
unixlib 0.1.1

Build failed:  -> task failed (err #1):
        {task: cxx unixlib.cc -> unixlib_1.o}
npm ERR! error installing unixlib@v0.1.1 Error: unixlib@v0.1.1 preinstall: `node-waf configure && node-waf build`
npm ERR! error installing unixlib@v0.1.1 `sh "-c" "node-waf configure && node-waf build"` failed with 1
npm ERR! error installing unixlib@v0.1.1     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing unixlib@v0.1.1     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing unixlib@v0.1.1     at ChildProcess.onexit (child_process.js:192:12)

> unixlib@v0.1.1 preuninstall /home/staylor/Documents/Quicktech/EmailService/node_modules/unixlib
> rm -rf build/*

npm ERR! unixlib@v0.1.1 preinstall: `node-waf configure && node-waf build`
npm ERR! `sh "-c" "node-waf configure && node-waf build"` failed with 1
npm ERR!
npm ERR! Failed at the unixlib@v0.1.1 preinstall script.
npm ERR! This is most likely a problem with the unixlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure && node-waf build
npm ERR! You can get their info via:
npm ERR!     npm owner ls unixlib
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.38-10-server
npm ERR! command "node" "/usr/local/bin/npm" "install" "unixlib@v0.1.1"
npm ERR! cwd /home/staylor/Documents/Quicktech/EmailService
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.103
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/staylor/Documents/Quicktech/EmailService/npm-debug.log
npm not ok

**Comment by sebastient** [comment]
The problem was that libpam0g-dev was not installed, a check for the required header files would be useful during the build.

**Comment by ditesh** [comment]
Thanks, I've added it.
